@echo off

REM   This script requires Administrator privileges

REM   Autogenerated by INF signing scripts (c) Secoh, 2020
REM   Licensed under the Apache License, Version 2.0

net session > nul 2>&1
if %errorlevel% equ 0 goto :doinstall

echo This script must be run with Administrator privileges
pause
exit

:haserror
echo The last operation returns error, see the above for details
pause
exit

:doinstall
certutil -addstore TrustedPublisher %~dp0sk_root.cer
if %errorlevel% neq 0 goto :haserror
certutil -addstore Root %~dp0sk_root.cer
if %errorlevel% neq 0 goto :haserror

